apiVersion: v1
kind: Pod
metadata:
  name: debug # pod name
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    purpose: debug
spec:
  containers:
  - name: debug # container name
    image: venkat787/debug:v1 # by default it will get from docker hub
    